version: '3.8'
services:
  backend:
    build: ./finalbooks_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ./finalbooks
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12Politech12
      - POSTGRES_DB=users_auth
      - POSTGRES_USER=postgres
